
resources:
  kafka:
    broker: "localhost:9092"
    repl-factor: 1
    consumergroupid: "assessment-evaluator"

debug: true
logging:
  level: debug
logging.level.org.springframework.kafka.config: debug
